algoritmo "conteAte10"
// Função :
// Autor :
// Data : 01/02/2021
// Seção de Declarações 
var
valor, salto, contador: inteiro

inicio
// Seção de Comandos 
  contador <- 0
  escreva("quer contar ate quanto? ")
  leia(valor)
  escreva("qual sera o valor do salto? ")
  leia(salto)
  enquanto (contador <=valor) faca
           escreval(contador)
           contador <- contador + salto
  fimenquanto
  escreval("terminei de contar")
fimalgoritmo
