algoritmo "ParamentrosporReferencia"
// Função :
// Autor :
// Data : 06/02/2021
// Seção de Declarações 
var
 x, y:inteiro
 procedimento Soma(var a, b: inteiro)
 inicio
 a<- a+1
 b<- b+2
 escreval("Valor de a = ", a)
 escreval("Valor de b = ", b)
 escreval("Soma a+b = ", a+b)
 fimprocedimento
inicio
// Seção de Comandos 
x<- 4
y<- 8
Soma(x, y)
escreval("Valor de x = ", x)
escreval("Valor de y = ", y)
fimalgoritmo
