algoritmo "semnome"
// Função :
// Autor :
// Data : 10/02/2021
// Seção de Declarações 
var
m: vetor [1..3, 1..3] de inteiro
l, c: inteiro
inicio
// Seção de Comandos 
para l<- 1 ate 3 faca
    para c<- 1 ate 3 faca
        escreva("Digite um valor: ")
        leia(m[l,c])
    fimpara
fimpara
para l <- 1 ate  3 faca
    para c <- 1 ate 3 faca
       escreva(m[l,c)
    fimpara
    escreval()
fimpara
fimalgoritmo
